services:
  - type: web
    name: pvpsit-facility-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/auth/profile
    envVars:
      - key: PORT
        value: 8080
      - key: APP_JWT_SECRET
        generateValue: true
